# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-17 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
